### ISSUE TITLE
how to build this project? 

### ISSUE THREAD

**Issue by arhampk09** [labstreaminglayer/App-Keyboard#2]
please give some instructions to build this project using vs code or visual studio

**Comment by tstenner** [comment]
The build script is in CMakeLists.txt, you can open it natively in Visual Studio. You also need to supply a path to a precompiled liblsl, the [documentation](https://labstreaminglayer.readthedocs.io/dev/app_dev.html#c-apps) explains it a bit better than I could.

In case you just want to use the input app, you can also download it directly from the [releases page](https://github.com/labstreaminglayer/App-Input/releases)

**Comment by arhampk09** [comment]
> 
> 
> The build script is in CMakeLists.txt, you can open it natively in Visual Studio. You also need to supply a path to a precompiled liblsl, the [documentation](https://labstreaminglayer.readthedocs.io/dev/app_dev.html#c-apps) explains it a bit better than I could.
> 
> In case you just want to use the input app, you can also download it directly from the [releases page](https://github.com/labstreaminglayer/App-Input/releases)

Thanks Dear
